# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
image:
  repository: registry.fke.fptcloud.com/762c8029-26d9-4bea-b461-989ee4d4890f/gardener-extension-private-network
  tag: latest
  pullPolicy: IfNotPresent

serviceName: private-network
replicaCount: 1
ignoreResources: false

controllers:
  lifecycle:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

gardener:
  version: ""
